#!/usr/bin/env python3
"""Regenerate site/sitemap.xml, site/sitemap/index.html and site/robots.txt.

Run from anywhere: python scripts/build-sitemap.py
The page list is PAGES below; each page's <lastmod> is the date of the last git commit that
touched its source file (left out if the file has no history). URLs always use BASE_URL, the
site's production address. The HTML page reuses the Boring Legal Stuff hub as its layout
(header, theme, footer).

Copyright (c) 2026 Stux.Group. All Rights Reserved.
"""
import html
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
BASE_URL = "https://githup.stux.group"

# (path, source file in the repo, label, description, priority, changefreq)
PAGES = [
    ("/", "site/index.html", "Home", "GitHup: uptime monitoring and status pages on GitHub.", "1.0", "monthly"),
    ("/docs/", "site/docs/index.html", "Docs", "How to set up and configure GitHup.", "0.8", "weekly"),
    ("/demo/", ".githup.yml", "Demo", "A live GitHup status page, built by the action from this website's own repository.", "0.7", "daily"),
    ("/changelogs/", "site/changelogs/index.html", "Changelogs", "Release notes for the website and the GitHup action.", "0.3", "monthly"),
    ("/legal/", "site/legal/index.html", "Boring Legal Stuff", "Privacy, terms, cookies, imprint, disclaimer and opt-out preferences.", "0.3", "yearly"),
    ("/legal/privacy/", "site/legal/privacy/index.html", "Privacy Policy", "What we collect (next to nothing) and why.", "0.2", "yearly"),
    ("/legal/terms/", "site/legal/terms/index.html", "Terms and Ethics", "Fair use of the website and the action.", "0.2", "yearly"),
    ("/legal/cookies/", "site/legal/cookies/index.html", "Cookies Policy", "We don't use any. Here's the detail.", "0.2", "yearly"),
    ("/legal/imprint/", "site/legal/imprint/index.html", "Imprint", "Who runs GitHup and how to reach us.", "0.2", "yearly"),
    ("/legal/disclaimer/", "site/legal/disclaimer/index.html", "Disclaimer", "Copyright, accuracy, accessibility and security.", "0.2", "yearly"),
    ("/legal/opt-out/", "site/legal/opt-out/index.html", "Opt-Out Preferences", "Your privacy choices, and why there's little to choose.", "0.2", "yearly"),
    ("/sitemap/", "site/sitemap/index.html", "Sitemap", "Every page on this site, with a link to the XML version.", "0.1", "monthly"),
]


def lastmod(rel: str) -> str:
    return subprocess.run(["git", "log", "-1", "--format=%cs", "--", rel], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()


def build_xml() -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, src, _label, _desc, priority, freq in PAGES:
        lines.append("  <url>")
        lines.append(f"    <loc>{html.escape(BASE_URL + loc)}</loc>")
        mod = lastmod(src)
        if mod:
            lines.append(f"    <lastmod>{mod}</lastmod>")
        lines.append(f"    <changefreq>{freq}</changefreq>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build_html() -> str:
    """The sitemap page, in the legal hub's layout."""
    page = (SITE / "legal" / "index.html").read_text(encoding="utf-8")
    desc = "Every page on GitHup's website, with a link to the XML sitemap."
    page = page.replace("Boring Legal Stuff · GitHup", "Sitemap · GitHup")
    page = re.sub(r'(<meta (?:name="description"|property="og:description") content=")[^"]*(">)',
                  rf"\g<1>{desc}\g<2>", page)
    page = page.replace("https://githup.stux.group/legal/", BASE_URL + "/sitemap/")
    page = page.replace(" / Boring Legal Stuff</p>", " / Sitemap</p>")
    page = page.replace("<h1>Boring Legal Stuff</h1>", "<h1>Sitemap</h1>")
    page = re.sub(r'<p class="sub">.*?</p>',
                  '<p class="sub">Every page on this site. Looking for the XML version? '
                  '<a href="/sitemap.xml">sitemap.xml</a></p>', page, count=1, flags=re.S)
    page = re.sub(r'\n    <p class="eff">.*?</p>', "", page, count=1, flags=re.S)
    items = []
    for loc, _src, label, d, _p, _f in PAGES:
        items.append(f'      <li><a href="{html.escape(loc)}"><strong>{html.escape(label)}</strong>'
                     f'<span>{html.escape(d)}</span><br>'
                     f'<span style="overflow-wrap: anywhere;">{html.escape(BASE_URL + loc)}</span></a></li>')
    start = page.index('<ul class="legal-list">')
    end = page.index("</ul>", start)
    page = page[:start] + '<ul class="legal-list">\n' + "\n".join(items) + "\n    " + page[end:]
    notice = "<!-- Generated by scripts/build-sitemap.py; edit the PAGES list there, then re-run it. -->\n"
    return page.replace("<body>\n", "<body>\n" + notice, 1)


def main() -> None:
    (SITE / "sitemap").mkdir(exist_ok=True)
    (SITE / "sitemap" / "index.html").write_text(build_html(), encoding="utf-8", newline="\n")
    (SITE / "sitemap.xml").write_text(build_xml(), encoding="utf-8", newline="\n")
    robots = SITE / "robots.txt"
    line = f"Sitemap: {BASE_URL}/sitemap.xml"
    text = robots.read_text(encoding="utf-8") if robots.exists() else "User-agent: *\nAllow: /\n"
    if line not in text:
        text = text.rstrip("\n") + "\n\n" + line + "\n"
    robots.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote site/sitemap.xml, site/sitemap/index.html and site/robots.txt for {BASE_URL} ({len(PAGES)} pages)")


if __name__ == "__main__":
    main()
